# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mojot/Documents/RoTrade/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mojot/Documents/RoTrade

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mojot/Documents/RoTrade/CMakeFiles /home/mojot/Documents/RoTrade//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mojot/Documents/RoTrade/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RoTrade

# Build rule for target.
RoTrade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RoTrade
.PHONY : RoTrade

# fast build rule for target.
RoTrade/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/build
.PHONY : RoTrade/fast

auto_trade_poster.o: auto_trade_poster.cpp.o
.PHONY : auto_trade_poster.o

# target to build an object file
auto_trade_poster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/auto_trade_poster.cpp.o
.PHONY : auto_trade_poster.cpp.o

auto_trade_poster.i: auto_trade_poster.cpp.i
.PHONY : auto_trade_poster.i

# target to preprocess a source file
auto_trade_poster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/auto_trade_poster.cpp.i
.PHONY : auto_trade_poster.cpp.i

auto_trade_poster.s: auto_trade_poster.cpp.s
.PHONY : auto_trade_poster.s

# target to generate assembly for a file
auto_trade_poster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/auto_trade_poster.cpp.s
.PHONY : auto_trade_poster.cpp.s

cli.o: cli.cpp.o
.PHONY : cli.o

# target to build an object file
cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/cli.cpp.o
.PHONY : cli.cpp.o

cli.i: cli.cpp.i
.PHONY : cli.i

# target to preprocess a source file
cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/cli.cpp.i
.PHONY : cli.cpp.i

cli.s: cli.cpp.s
.PHONY : cli.s

# target to generate assembly for a file
cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/cli.cpp.s
.PHONY : cli.cpp.s

data_query.o: data_query.cpp.o
.PHONY : data_query.o

# target to build an object file
data_query.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/data_query.cpp.o
.PHONY : data_query.cpp.o

data_query.i: data_query.cpp.i
.PHONY : data_query.i

# target to preprocess a source file
data_query.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/data_query.cpp.i
.PHONY : data_query.cpp.i

data_query.s: data_query.cpp.s
.PHONY : data_query.s

# target to generate assembly for a file
data_query.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/data_query.cpp.s
.PHONY : data_query.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/main.cpp.s
.PHONY : main.cpp.s

trade_ads.o: trade_ads.cpp.o
.PHONY : trade_ads.o

# target to build an object file
trade_ads.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/trade_ads.cpp.o
.PHONY : trade_ads.cpp.o

trade_ads.i: trade_ads.cpp.i
.PHONY : trade_ads.i

# target to preprocess a source file
trade_ads.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/trade_ads.cpp.i
.PHONY : trade_ads.cpp.i

trade_ads.s: trade_ads.cpp.s
.PHONY : trade_ads.s

# target to generate assembly for a file
trade_ads.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/trade_ads.cpp.s
.PHONY : trade_ads.cpp.s

trade_eval.o: trade_eval.cpp.o
.PHONY : trade_eval.o

# target to build an object file
trade_eval.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/trade_eval.cpp.o
.PHONY : trade_eval.cpp.o

trade_eval.i: trade_eval.cpp.i
.PHONY : trade_eval.i

# target to preprocess a source file
trade_eval.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/trade_eval.cpp.i
.PHONY : trade_eval.cpp.i

trade_eval.s: trade_eval.cpp.s
.PHONY : trade_eval.s

# target to generate assembly for a file
trade_eval.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/trade_eval.cpp.s
.PHONY : trade_eval.cpp.s

trade_filter.o: trade_filter.cpp.o
.PHONY : trade_filter.o

# target to build an object file
trade_filter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/trade_filter.cpp.o
.PHONY : trade_filter.cpp.o

trade_filter.i: trade_filter.cpp.i
.PHONY : trade_filter.i

# target to preprocess a source file
trade_filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/trade_filter.cpp.i
.PHONY : trade_filter.cpp.i

trade_filter.s: trade_filter.cpp.s
.PHONY : trade_filter.s

# target to generate assembly for a file
trade_filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/trade_filter.cpp.s
.PHONY : trade_filter.cpp.s

web_scraper.o: web_scraper.cpp.o
.PHONY : web_scraper.o

# target to build an object file
web_scraper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/web_scraper.cpp.o
.PHONY : web_scraper.cpp.o

web_scraper.i: web_scraper.cpp.i
.PHONY : web_scraper.i

# target to preprocess a source file
web_scraper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/web_scraper.cpp.i
.PHONY : web_scraper.cpp.i

web_scraper.s: web_scraper.cpp.s
.PHONY : web_scraper.s

# target to generate assembly for a file
web_scraper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoTrade.dir/build.make CMakeFiles/RoTrade.dir/web_scraper.cpp.s
.PHONY : web_scraper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RoTrade"
	@echo "... auto_trade_poster.o"
	@echo "... auto_trade_poster.i"
	@echo "... auto_trade_poster.s"
	@echo "... cli.o"
	@echo "... cli.i"
	@echo "... cli.s"
	@echo "... data_query.o"
	@echo "... data_query.i"
	@echo "... data_query.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... trade_ads.o"
	@echo "... trade_ads.i"
	@echo "... trade_ads.s"
	@echo "... trade_eval.o"
	@echo "... trade_eval.i"
	@echo "... trade_eval.s"
	@echo "... trade_filter.o"
	@echo "... trade_filter.i"
	@echo "... trade_filter.s"
	@echo "... web_scraper.o"
	@echo "... web_scraper.i"
	@echo "... web_scraper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

